# Etapa 1 buildando aplicação
FROM node:16.20-alpine

# defindo workdir para pasta app
WORKDIR /app

COPY . .

#instalando dependêcias
RUN npm install
RUN npx prisma generate

# compilando build da aplicação
CMD ["npm", "run" , "start:dev"]